FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app
COPY . .
RUN dotnet publish -c Release -o /app/publish
WORKDIR /app/publish
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "Plantilla_practicadll"]